import com.yandex.div.gradle.FileExtensions
import groovy.json.JsonOutput

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.screenshotTestPlugin)
    alias(libs.plugins.roborazzi)
}

apply from: "${project.projectDir}/../div-common.gradle"
apply from: "${project.projectDir}/../div-tests.gradle"

repositories {
    maven { url 'https://repo.gradle.org/gradle/libs-releases' }
}

android {
    namespace = 'com.yandex.divkit.demo'

    testOptions.unitTests.all {
        systemProperty 'robolectric.pixelCopyRenderMode', 'hardware'
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    defaultConfig {
        versionCode = divkitVersion.versionCode + divkitVersion.buildNumber
        buildConfigField "int", "BUILD_NUMBER", "${divkitVersion.buildNumber}"
        buildConfigField "String", "METRICA_API_KEY", JsonOutput.toJson(providers.gradleProperty("metricaApiKey").getOrElse(""))
        buildConfigField "boolean", "THROW_ASSERTS", "${!providers.gradleProperty("screenshot-tests").isPresent()}"
        buildConfigField "String", "HTTP_HEADERS", JsonOutput.toJson(providers.gradleProperty("httpHeaders").getOrElse("{}"))

        testInstrumentationRunner "io.qameta.allure.android.runners.AllureAndroidJUnitRunner"
        testInstrumentationRunnerArguments useTestStorageService: 'true'
        if (providers.gradleProperty("compare-compose").isPresent()) {
            testInstrumentationRunnerArguments compareComposeWithView: 'true'
        }

        providers.gradleProperty("shardIndex").orNull?.with { index ->
            testInstrumentationRunnerArguments.shardIndex = index
        }
        providers.gradleProperty("numShards").orNull?.with { shards ->
            testInstrumentationRunnerArguments.numShards = shards
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    sourceSets {
        main {
            assets.srcDirs += "../../../test_data/"
        }

        test {
            kotlin.srcDirs += 'src/sharedTest/java'
            resources.srcDirs += 'src/main/assets' // needed to access assets in unit tests.
        }

        androidTest {
            kotlin.srcDirs += 'src/sharedTest/java'
            kotlin.srcDirs += 'src/screenshotTest/java'
        }
    }
}

dependencies {
    implementation project(path: ':assertion')
    implementation project(path: ':backdrop-effect')
    implementation project(path: ':coil')
    implementation project(path: ':coil-core')
    implementation project(path: ':compose')
    implementation project(path: ':compose-lottie')
    implementation project(path: ':compose-video-view-based')
    implementation project(path: ':div')
    implementation project(path: ':div-gesture')
    implementation project(path: ':div-lottie')
    implementation project(path: ':div-markdown')
    implementation project(path: ':div-network')
    implementation project(path: ':div-pinch-to-zoom')
    implementation project(path: ':div-rive')
    implementation project(path: ':div-shimmer')
    implementation project(path: ':div-shine')
    implementation project(path: ':div-size-provider')
    implementation project(path: ':div-video-m3')
    implementation project(path: ':divkit-regression-testing')
    implementation project(path: ':fonts')
    implementation project(path: ':glide')
    implementation project(path: ':logging')
    implementation project(path: ':test-utils')
    implementation project(path: ':utils')

    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.foundation
    implementation libs.androidx.compose.ui
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.material
    implementation libs.androidx.recyclerview
    implementation libs.androidx.transition
    implementation libs.androidx.work

    implementation(libs.appmetrica.lib) {
        exclude group: 'io.appmetrica.analytics', module: 'analytics-identifiers'
    }

    implementation libs.javax
    implementation libs.markwon
    implementation libs.nvWebsocket
    implementation libs.okhttp
    implementation libs.stetho.core
    implementation libs.stetho.okhttp3
    implementation libs.yatagan.api.public
    implementation libs.zxing.embedded
    implementation libs.zxing.core

    androidTestUtil libs.androidx.test.services
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation project(path: ':screenshot-test-runtime')
    androidTestImplementation project(path: ':ui-test-common')
    androidTestImplementation libs.allure.android
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    androidTestImplementation libs.androidx.lifecycle.viewmodel
    androidTestImplementation libs.androidx.test.uiautomator
    androidTestImplementation libs.androidx.viewpager2
    androidTestImplementation libs.hamcrest

    testImplementation libs.androidx.test.core
    testImplementation libs.androidx.espresso.core
    testImplementation libs.json
    testImplementation libs.roborazzi
    testImplementation libs.roborazzi.junit.rule
    testImplementation libs.webp.imageio
}

roborazzi {
    outputDir = file(
            'src/test/screenshots/com.yandex.divkit.demo.screenshot.ViewRoborazziScreenshotTest'
    )
}

tasks.withType(Test).configureEach {
    providers.gradleProperty('divkitTestFilter').orNull?.with { filter ->
        systemProperty 'divkit.test.filter', filter
    }
}

screenshotTests {
    def isInIde = providers.systemProperty("idea.active").map(Boolean::parseBoolean).getOrElse(false)
    enabled = providers.gradleProperty("screenshot-tests").isPresent() || isInIde
    enableComparison = !providers.gradleProperty("disable-screenshot-comparison").isPresent()
    strictComparison = providers.gradleProperty("screenshot-strict-comparison").isPresent()
    ignoreFailures = providers.gradleProperty("screenshot-ignore-failures").isPresent()
    selectedReferencePrefix = providers.gradleProperty("screenshot-selected-reference-prefix").getOrElse("")
    testAnnotations = ["com.yandex.test.screenshot.Screenshot"]
    referencesDir = "src/screenshotTest/screenshots"
}

base {
    archivesName = divkitVersion.buildNumber != 0 ?
            "${project.name}-v${divkitVersion.baseVersionName}-b${divkitVersion.buildNumber}" :
            "${project.name}-v${divkitVersion.baseVersionName}"
}

FileExtensions.ifExists("${project.projectDir}/build.internal.gradle") {
    apply from: it
}
