import Serialization

extension DivData: ContextDeserializable {}
extension Div: ContextDeserializable {}
extension DivImage: ContextDeserializable {}
extension DivGifImage: ContextDeserializable {}
extension DivText: ContextDeserializable {}
extension DivSeparator: ContextDeserializable {}
extension DivContainer: ContextDeserializable {}
extension DivGrid: ContextDeserializable {}
extension DivGallery: ContextDeserializable {}
extension DivPager: ContextDeserializable {}
extension DivTabs: ContextDeserializable {}
extension DivState: ContextDeserializable {}
extension DivCustom: ContextDeserializable {}
extension DivIndicator: ContextDeserializable {}
extension DivSlider: ContextDeserializable {}
extension DivSwitch: ContextDeserializable {}
extension DivInput: ContextDeserializable {}
extension DivSelect: ContextDeserializable {}
extension DivVideo: ContextDeserializable {}
extension DivAction: ContextDeserializable {}
extension DivVisibilityAction: ContextDeserializable {}
extension DivDisappearAction: ContextDeserializable {}
extension DivVariable: ContextDeserializable {}
extension DivPatch: ContextDeserializable {}
extension DivTimer: ContextDeserializable {}
extension DivTrigger: ContextDeserializable {}
extension DivFunction: ContextDeserializable {}
