"""divkit_rs — Fast Rust-backed DivKit JSON builder."""

from divkit_rs._native import (
    # Base class
    PyDivEntity,
    # Top-level helpers
    PyDivData as DivData,
    PyDivDataState as DivDataState,
    make_div,
    make_card,
    # ----------------------------------------------------------------
    # Size types
    # ----------------------------------------------------------------
    DivFixedSize,
    DivMatchParentSize,
    DivWrapContentSize,
    DivPercentageSize,
    # ----------------------------------------------------------------
    # Basic / structural types
    # ----------------------------------------------------------------
    DivAbsoluteEdgeInsets,
    DivAccessibility,
    DivAspect,
    DivBase,
    DivBlur,
    DivBorder,
    DivCornersRadius,
    DivDimension,
    DivEdgeInsets,
    DivExtension,
    DivFocus,
    DivFocusNextFocusIds,
    DivFunction,
    DivFunctionArgument,
    DivLayoutProvider,
    DivPoint,
    DivShadow,
    DivSizeUnitValue,
    DivStroke,
    DivStrokeStyleDashed,
    DivStrokeStyleSolid,
    DivTransform,
    DivTransitionBase,
    # ----------------------------------------------------------------
    # Actions
    # ----------------------------------------------------------------
    DivAction,
    DivActionAnimatorStart,
    DivActionAnimatorStop,
    DivActionArrayInsertValue,
    DivActionArrayRemoveValue,
    DivActionArraySetValue,
    DivActionClearFocus,
    DivActionCopyToClipboard,
    DivActionCustom,
    DivActionDictSetValue,
    DivActionDownload,
    DivActionFocusElement,
    DivActionHideTooltip,
    DivActionMenuItem,
    DivActionScrollBy,
    DivActionScrollTo,
    DivActionSetState,
    DivActionSetStoredValue,
    DivActionSetVariable,
    DivActionShowTooltip,
    DivActionSubmit,
    DivActionSubmitRequest,
    DivActionTimer,
    DivActionUpdateStructure,
    DivActionVideo,
    RequestHeader,
    # ----------------------------------------------------------------
    # Sight / visibility / disappear actions
    # ----------------------------------------------------------------
    DivDisappearAction,
    DivDownloadCallbacks,
    DivSightAction,
    DivVisibilityAction,
    # ----------------------------------------------------------------
    # Background types
    # ----------------------------------------------------------------
    DivCloudBackground,
    DivImageBackground,
    DivLinearGradient,
    DivLinearGradientColorPoint,
    DivNinePatchBackground,
    # NOTE: DivGradientBackground was renamed to DivLinearGradient in the schema.
    # The alias below preserves backward compatibility with pydivkit code.
    DivRadialGradient,
    DivRadialGradientColorPoint,
    DivRadialGradientFixedCenter,
    DivRadialGradientRelativeCenter,
    DivRadialGradientRelativeRadius,
    DivSolidBackground,
    # ----------------------------------------------------------------
    # Shape types
    # ----------------------------------------------------------------
    DivCircleShape,
    DivRoundedRectangleShape,
    DivShapeDrawable,
    # ----------------------------------------------------------------
    # Transition types
    # ----------------------------------------------------------------
    DivAppearanceSetTransition,
    DivChangeBoundsTransition,
    DivChangeSetTransition,
    DivFadeTransition,
    DivScaleTransition,
    DivSlideTransition,
    # ----------------------------------------------------------------
    # Transformation types
    # ----------------------------------------------------------------
    DivFixedTranslation,
    DivPercentageTranslation,
    DivPivotFixed,
    DivPivotPercentage,
    DivRotationTransformation,
    DivTranslationTransformation,
    # ----------------------------------------------------------------
    # Animation / animator types
    # ----------------------------------------------------------------
    DivAnimation,
    DivAnimatorBase,
    DivColorAnimator,
    DivNumberAnimator,
    # ----------------------------------------------------------------
    # Main div components
    # ----------------------------------------------------------------
    DivContainer,
    DivContainerSeparator,
    DivCustom,
    DivGallery,
    DivGifImage,
    DivGrid,
    DivImage,
    DivIndicator,
    DivInput,
    DivInputNativeInterface,
    DivPager,
    DivSelect,
    DivSelectOption,
    DivSeparator,
    DivSeparatorDelimiterStyle,
    DivSlider,
    DivSliderRange,
    DivSliderTextStyle,
    DivState,
    DivStateState,
    DivSwitch,
    DivTabs,
    DivTabsItem,
    DivTabsTabTitleDelimiter,
    DivTabsTabTitleStyle,
    DivText,
    DivVideo,
    DivVideoSource,
    DivVideoSourceResolution,
    # ----------------------------------------------------------------
    # Text sub-types
    # ----------------------------------------------------------------
    DivTextEllipsis,
    DivTextImage,
    DivTextRange,
    DivTextRangeBorder,
    DivTextRangeMaskBase,
    DivTextRangeMaskParticles,
    DivTextRangeMaskSolid,
    ImageAccessibility,
    # ----------------------------------------------------------------
    # Input mask / filter / validator types
    # ----------------------------------------------------------------
    DivCurrencyInputMask,
    DivFixedLengthInputMask,
    DivFixedLengthInputMaskPatternElement,
    DivInputFilterExpression,
    DivInputFilterRegex,
    DivInputMaskBase,
    DivInputValidatorBase,
    DivInputValidatorExpression,
    DivInputValidatorRegex,
    DivPhoneInputMask,
    # ----------------------------------------------------------------
    # Indicator / pager layout types
    # ----------------------------------------------------------------
    DivDefaultIndicatorItemPlacement,
    DivStretchIndicatorItemPlacement,
    DivNeighbourPageSize,
    DivPageContentSize,
    DivPageSize,
    DivPageTransformationOverlap,
    DivPageTransformationSlide,
    # ----------------------------------------------------------------
    # Filter types
    # ----------------------------------------------------------------
    DivFilterRtlMirror,
    # ----------------------------------------------------------------
    # Tooltip types
    # ----------------------------------------------------------------
    DivTooltip,
    DivTooltipModeModal,
    DivTooltipModeNonModal,
    # ----------------------------------------------------------------
    # Trigger / timer types
    # ----------------------------------------------------------------
    DivTrigger,
    DivTimer,
    # ----------------------------------------------------------------
    # Patch types
    # ----------------------------------------------------------------
    DivPatch,
    DivPatchChange,
    # ----------------------------------------------------------------
    # Collection item builder
    # ----------------------------------------------------------------
    DivCollectionItemBuilder,
    DivCollectionItemBuilderPrototype,
    # ----------------------------------------------------------------
    # Count types
    # ----------------------------------------------------------------
    DivFixedCount,
    DivInfinityCount,
    # ----------------------------------------------------------------
    # Scroll destination types
    # ----------------------------------------------------------------
    EndDestination,
    IndexDestination,
    OffsetDestination,
    StartDestination,
    # ----------------------------------------------------------------
    # Variable types
    # ----------------------------------------------------------------
    ArrayVariable,
    BooleanVariable,
    ColorVariable,
    DictVariable,
    IntegerVariable,
    NumberVariable,
    PropertyVariable,
    StringVariable,
    UrlVariable,
    # ----------------------------------------------------------------
    # Typed value types
    # ----------------------------------------------------------------
    ArrayValue,
    BooleanValue,
    ColorValue,
    ContentText,
    ContentUrl,
    DictValue,
    IntegerValue,
    NumberValue,
    StringValue,
    UrlValue,
    # ----------------------------------------------------------------
    # Enums
    # ----------------------------------------------------------------
    AccessibilityType,
    DelimiterStyleOrientation,
    DivAccessibilityMode,
    DivAccessibilityType,
    DivActionScrollByOverflow,
    DivActionTarget,
    DivActionTimerAction,
    DivActionVideoAction,
    DivAlignmentHorizontal,
    DivAlignmentVertical,
    DivAnimationDirection,
    DivAnimationInterpolator,
    DivAnimationName,
    DivBlendMode,
    DivContainerLayoutMode,
    DivContainerOrientation,
    DivContentAlignmentHorizontal,
    DivContentAlignmentVertical,
    DivEvaluableType,
    DivFontWeight,
    DivGalleryCrossContentAlignment,
    DivGalleryOrientation,
    DivGalleryScrollbar,
    DivGalleryScrollMode,
    DivImageScale,
    DivIndicatorAnimation,
    DivInputAutocapitalization,
    DivInputEnterKeyType,
    DivInputKeyboardType,
    DivLineStyle,
    DivPagerItemAlignment,
    DivPagerOrientation,
    DivPatchMode,
    DivRadialGradientRelativeRadiusValue,
    DivSizeUnit,
    DivSlideTransitionEdge,
    DivTextAlignmentVertical,
    DivTextTruncate,
    DivTooltipPosition,
    DivTransitionSelector,
    DivTransitionTrigger,
    DivTriggerMode,
    DivVideoScale,
    DivVisibility,
    ImageIndexingDirection,
    RequestMethod,
    TabTitleStyleAnimationType,
    # ----------------------------------------------------------------
    # Type aliases (Union types)
    # ----------------------------------------------------------------
    Div,
    DivActionCopyToClipboardContent,
    DivActionScrollDestination,
    DivActionTyped,
    DivAnimator,
    DivAppearanceTransition,
    DivBackground,
    DivChangeTransition,
    DivCount,
    DivDrawable,
    DivFilter,
    DivIndicatorItemPlacement,
    DivInputFilter,
    DivInputMask,
    DivInputValidator,
    DivPageTransformation,
    DivPagerLayoutMode,
    DivPivot,
    DivRadialGradientCenter,
    DivRadialGradientRadius,
    DivShape,
    DivSize,
    DivStrokeStyle,
    DivTextGradient,
    DivTextRangeBackground,
    DivTextRangeMask,
    DivTooltipMode,
    DivTransformation,
    DivTranslation,
    DivTypedValue,
    DivVariable,
)

# Backward-compatible alias: pydivkit used DivGradientBackground,
# the schema now calls it DivLinearGradient.
DivGradientBackground = DivLinearGradient

__all__ = [
    "PyDivEntity",
    "DivData",
    "DivDataState",
    "make_div",
    "make_card",
    # Size types
    "DivFixedSize",
    "DivMatchParentSize",
    "DivWrapContentSize",
    "DivPercentageSize",
    # Basic / structural types
    "DivAbsoluteEdgeInsets",
    "DivAccessibility",
    "DivAspect",
    "DivBase",
    "DivBlur",
    "DivBorder",
    "DivCornersRadius",
    "DivDimension",
    "DivEdgeInsets",
    "DivExtension",
    "DivFocus",
    "DivFocusNextFocusIds",
    "DivFunction",
    "DivFunctionArgument",
    "DivLayoutProvider",
    "DivPoint",
    "DivShadow",
    "DivSizeUnitValue",
    "DivStroke",
    "DivStrokeStyleDashed",
    "DivStrokeStyleSolid",
    "DivTransform",
    "DivTransitionBase",
    # Actions
    "DivAction",
    "DivActionAnimatorStart",
    "DivActionAnimatorStop",
    "DivActionArrayInsertValue",
    "DivActionArrayRemoveValue",
    "DivActionArraySetValue",
    "DivActionClearFocus",
    "DivActionCopyToClipboard",
    "DivActionCustom",
    "DivActionDictSetValue",
    "DivActionDownload",
    "DivActionFocusElement",
    "DivActionHideTooltip",
    "DivActionMenuItem",
    "DivActionScrollBy",
    "DivActionScrollTo",
    "DivActionSetState",
    "DivActionSetStoredValue",
    "DivActionSetVariable",
    "DivActionShowTooltip",
    "DivActionSubmit",
    "DivActionSubmitRequest",
    "DivActionTimer",
    "DivActionUpdateStructure",
    "DivActionVideo",
    "RequestHeader",
    # Sight / visibility / disappear actions
    "DivDisappearAction",
    "DivDownloadCallbacks",
    "DivSightAction",
    "DivVisibilityAction",
    # Background types
    "DivCloudBackground",
    "DivImageBackground",
    "DivGradientBackground",  # compat alias for DivLinearGradient
    "DivLinearGradient",
    "DivLinearGradientColorPoint",
    "DivNinePatchBackground",
    "DivRadialGradient",
    "DivRadialGradientColorPoint",
    "DivRadialGradientFixedCenter",
    "DivRadialGradientRelativeCenter",
    "DivRadialGradientRelativeRadius",
    "DivSolidBackground",
    # Shape types
    "DivCircleShape",
    "DivRoundedRectangleShape",
    "DivShapeDrawable",
    # Transition types
    "DivAppearanceSetTransition",
    "DivChangeBoundsTransition",
    "DivChangeSetTransition",
    "DivFadeTransition",
    "DivScaleTransition",
    "DivSlideTransition",
    # Transformation types
    "DivFixedTranslation",
    "DivPercentageTranslation",
    "DivPivotFixed",
    "DivPivotPercentage",
    "DivRotationTransformation",
    "DivTranslationTransformation",
    # Animation / animator types
    "DivAnimation",
    "DivAnimatorBase",
    "DivColorAnimator",
    "DivNumberAnimator",
    # Main div components
    "DivContainer",
    "DivContainerSeparator",
    "DivCustom",
    "DivGallery",
    "DivGifImage",
    "DivGrid",
    "DivImage",
    "DivIndicator",
    "DivInput",
    "DivInputNativeInterface",
    "DivPager",
    "DivSelect",
    "DivSelectOption",
    "DivSeparator",
    "DivSeparatorDelimiterStyle",
    "DivSlider",
    "DivSliderRange",
    "DivSliderTextStyle",
    "DivState",
    "DivStateState",
    "DivSwitch",
    "DivTabs",
    "DivTabsItem",
    "DivTabsTabTitleDelimiter",
    "DivTabsTabTitleStyle",
    "DivText",
    "DivVideo",
    "DivVideoSource",
    "DivVideoSourceResolution",
    # Text sub-types
    "DivTextEllipsis",
    "DivTextImage",
    "DivTextRange",
    "DivTextRangeBorder",
    "DivTextRangeMaskBase",
    "DivTextRangeMaskParticles",
    "DivTextRangeMaskSolid",
    "ImageAccessibility",
    # Input mask / filter / validator types
    "DivCurrencyInputMask",
    "DivFixedLengthInputMask",
    "DivFixedLengthInputMaskPatternElement",
    "DivInputFilterExpression",
    "DivInputFilterRegex",
    "DivInputMaskBase",
    "DivInputValidatorBase",
    "DivInputValidatorExpression",
    "DivInputValidatorRegex",
    "DivPhoneInputMask",
    # Indicator / pager layout types
    "DivDefaultIndicatorItemPlacement",
    "DivStretchIndicatorItemPlacement",
    "DivNeighbourPageSize",
    "DivPageContentSize",
    "DivPageSize",
    "DivPageTransformationOverlap",
    "DivPageTransformationSlide",
    # Filter types
    "DivFilterRtlMirror",
    # Tooltip types
    "DivTooltip",
    "DivTooltipModeModal",
    "DivTooltipModeNonModal",
    # Trigger / timer types
    "DivTrigger",
    "DivTimer",
    # Patch types
    "DivPatch",
    "DivPatchChange",
    # Collection item builder
    "DivCollectionItemBuilder",
    "DivCollectionItemBuilderPrototype",
    # Count types
    "DivFixedCount",
    "DivInfinityCount",
    # Scroll destination types
    "EndDestination",
    "IndexDestination",
    "OffsetDestination",
    "StartDestination",
    # Variable types
    "ArrayVariable",
    "BooleanVariable",
    "ColorVariable",
    "DictVariable",
    "IntegerVariable",
    "NumberVariable",
    "PropertyVariable",
    "StringVariable",
    "UrlVariable",
    # Typed value types
    "ArrayValue",
    "BooleanValue",
    "ColorValue",
    "ContentText",
    "ContentUrl",
    "DictValue",
    "IntegerValue",
    "NumberValue",
    "StringValue",
    "UrlValue",
    # Enums
    "AccessibilityType",
    "DelimiterStyleOrientation",
    "DivAccessibilityMode",
    "DivAccessibilityType",
    "DivActionScrollByOverflow",
    "DivActionTarget",
    "DivActionTimerAction",
    "DivActionVideoAction",
    "DivAlignmentHorizontal",
    "DivAlignmentVertical",
    "DivAnimationDirection",
    "DivAnimationInterpolator",
    "DivAnimationName",
    "DivBlendMode",
    "DivContainerLayoutMode",
    "DivContainerOrientation",
    "DivContentAlignmentHorizontal",
    "DivContentAlignmentVertical",
    "DivEvaluableType",
    "DivFontWeight",
    "DivGalleryCrossContentAlignment",
    "DivGalleryOrientation",
    "DivGalleryScrollbar",
    "DivGalleryScrollMode",
    "DivImageScale",
    "DivIndicatorAnimation",
    "DivInputAutocapitalization",
    "DivInputEnterKeyType",
    "DivInputKeyboardType",
    "DivLineStyle",
    "DivPagerItemAlignment",
    "DivPagerOrientation",
    "DivPatchMode",
    "DivRadialGradientRelativeRadiusValue",
    "DivSizeUnit",
    "DivSlideTransitionEdge",
    "DivTextAlignmentVertical",
    "DivTextTruncate",
    "DivTooltipPosition",
    "DivTransitionSelector",
    "DivTransitionTrigger",
    "DivTriggerMode",
    "DivVideoScale",
    "DivVisibility",
    "ImageIndexingDirection",
    "RequestMethod",
    "TabTitleStyleAnimationType",
    # Type aliases (Union types)
    "Div",
    "DivActionCopyToClipboardContent",
    "DivActionScrollDestination",
    "DivActionTyped",
    "DivAnimator",
    "DivAppearanceTransition",
    "DivBackground",
    "DivChangeTransition",
    "DivCount",
    "DivDrawable",
    "DivFilter",
    "DivIndicatorItemPlacement",
    "DivInputFilter",
    "DivInputMask",
    "DivInputValidator",
    "DivPageTransformation",
    "DivPagerLayoutMode",
    "DivPivot",
    "DivRadialGradientCenter",
    "DivRadialGradientRadius",
    "DivShape",
    "DivSize",
    "DivStrokeStyle",
    "DivTextGradient",
    "DivTextRangeBackground",
    "DivTextRangeMask",
    "DivTooltipMode",
    "DivTransformation",
    "DivTranslation",
    "DivTypedValue",
    "DivVariable",
]
