apply plugin: "kotlin-android"
apply plugin: "kotlin-allopen"

kotlin {
    jvmToolchain(libs.versions.jvm.toolchain.get().toInteger())
}

android {
    compileSdk = libs.versions.android.compileSdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInteger()
        targetSdk = libs.versions.android.targetSdk.get().toInteger()

        versionName = divkitVersion.baseVersionName
        versionCode = divkitVersion.versionCode

        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
}

tasks.register('sourceJar', Jar) {
    from android.sourceSets.main.java.srcDirs
    archiveClassifier = "sources"
}

allOpen {
    annotation("com.yandex.div.core.annotations.Mockable")
}
