kotlin {
    jvmToolchain(libs.versions.jvm.toolchain.get().toInteger())
}

android {
    compileSdk = libs.versions.android.compileSdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInteger()
        targetSdk = libs.versions.android.targetSdk.get().toInteger()

        versionName = divkitVersion.baseVersionName
        versionCode = divkitVersion.versionCode

        vectorDrawables.useSupportLibrary = true
    }

    lint {
        // Can be removed after AGP 9.2+ upgrade
        disable.add("WrongConstant")
    }
}

tasks.register('sourceJar', Jar) {
    from android.sourceSets.main.java.srcDirs
    archiveClassifier = "sources"
}
