include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - require_trailing_commas
    - prefer_const_constructors
    - directives_ordering
