OWNER(g:divkit)

PY3_LIBRARY()

PY_SRCS(
    TOP_LEVEL
    pydivkit/__init__.py
    pydivkit/core/__init__.py
    pydivkit/core/compat.py
    pydivkit/core/entities.py
    pydivkit/core/fields.py
    pydivkit/core/types/__init__.py
    pydivkit/core/types/union.py
    pydivkit/div/__init__.py
    pydivkit/div/boolean_variable.py
    pydivkit/div/color_variable.py
    pydivkit/div/div.py
    pydivkit/div/div_absolute_edge_insets.py
    pydivkit/div/div_accessibility.py
    pydivkit/div/div_action.py
    pydivkit/div/div_alignment_horizontal.py
    pydivkit/div/div_alignment_vertical.py
    pydivkit/div/div_animation.py
    pydivkit/div/div_animation_interpolator.py
    pydivkit/div/div_appearance_set_transition.py
    pydivkit/div/div_appearance_transition.py
    pydivkit/div/div_aspect.py
    pydivkit/div/div_background.py
    pydivkit/div/div_base.py
    pydivkit/div/div_blend_mode.py
    pydivkit/div/div_border.py
    pydivkit/div/div_change_bounds_transition.py
    pydivkit/div/div_change_set_transition.py
    pydivkit/div/div_change_transition.py
    pydivkit/div/div_circle_shape.py
    pydivkit/div/div_container.py
    pydivkit/div/div_corners_radius.py
    pydivkit/div/div_count.py
    pydivkit/div/div_custom.py
    pydivkit/div/div_data.py
    pydivkit/div/div_dimension.py
    pydivkit/div/div_download_callbacks.py
    pydivkit/div/div_drawable.py
    pydivkit/div/div_edge_insets.py
    pydivkit/div/div_extension.py
    pydivkit/div/div_fade_transition.py
    pydivkit/div/div_fixed_count.py
    pydivkit/div/div_fixed_size.py
    pydivkit/div/div_focus.py
    pydivkit/div/div_font_family.py
    pydivkit/div/div_font_weight.py
    pydivkit/div/div_gallery.py
    pydivkit/div/div_gif_image.py
    pydivkit/div/div_grid.py
    pydivkit/div/div_image.py
    pydivkit/div/div_image_background.py
    pydivkit/div/div_image_scale.py
    pydivkit/div/div_indicator.py
    pydivkit/div/div_infinity_count.py
    pydivkit/div/div_input.py
    pydivkit/div/div_line_style.py
    pydivkit/div/div_linear_gradient.py
    pydivkit/div/div_match_parent_size.py
    pydivkit/div/div_neighbour_page_size.py
    pydivkit/div/div_nine_patch_background.py
    pydivkit/div/div_page_size.py
    pydivkit/div/div_pager.py
    pydivkit/div/div_pager_layout_mode.py
    pydivkit/div/div_patch.py
    pydivkit/div/div_percentage_size.py
    pydivkit/div/div_pivot.py
    pydivkit/div/div_pivot_fixed.py
    pydivkit/div/div_pivot_percentage.py
    pydivkit/div/div_point.py
    pydivkit/div/div_radial_gradient.py
    pydivkit/div/div_radial_gradient_center.py
    pydivkit/div/div_radial_gradient_fixed_center.py
    pydivkit/div/div_radial_gradient_radius.py
    pydivkit/div/div_radial_gradient_relative_center.py
    pydivkit/div/div_radial_gradient_relative_radius.py
    pydivkit/div/div_rounded_rectangle_shape.py
    pydivkit/div/div_scale_transition.py
    pydivkit/div/div_separator.py
    pydivkit/div/div_shadow.py
    pydivkit/div/div_shape.py
    pydivkit/div/div_shape_drawable.py
    pydivkit/div/div_size.py
    pydivkit/div/div_size_unit.py
    pydivkit/div/div_slide_transition.py
    pydivkit/div/div_slider.py
    pydivkit/div/div_solid_background.py
    pydivkit/div/div_state.py
    pydivkit/div/div_stroke.py
    pydivkit/div/div_tabs.py
    pydivkit/div/div_text.py
    pydivkit/div/div_text_gradient.py
    pydivkit/div/div_tooltip.py
    pydivkit/div/div_transform.py
    pydivkit/div/div_transition_base.py
    pydivkit/div/div_transition_selector.py
    pydivkit/div/div_transition_trigger.py
    pydivkit/div/div_trigger.py
    pydivkit/div/div_variable.py
    pydivkit/div/div_visibility.py
    pydivkit/div/div_visibility_action.py
    pydivkit/div/div_wrap_content_size.py
    pydivkit/div/integer_variable.py
    pydivkit/div/number_variable.py
    pydivkit/div/string_variable.py
    pydivkit/div/url_variable.py
)

PEERDIR(
    contrib/python/inflection
)

END()

RECURSE_FOR_TESTS(
    tests
)
