"""empty message

Revision ID: 27b1565deb2c
Revises: 
Create Date: 2022-11-16 11:49:26.629160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27b1565deb2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), nullable=True),
    sa.Column('title', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates2tags',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('template_id', postgresql.UUID(), nullable=False),
    sa.Column('tag_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates2tags_tag_id'), 'templates2tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_templates2tags_template_id'), 'templates2tags', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates2tags_template_id'), table_name='templates2tags')
    op.drop_index(op.f('ix_templates2tags_tag_id'), table_name='templates2tags')
    op.drop_table('templates2tags')
    op.drop_table('templates')
    op.drop_table('tags')
    # ### end Alembic commands ###
