"""empty message

Revision ID: 4c22d43e7c36
Revises: a0889f273a65
Create Date: 2022-11-17 15:52:20.787886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c22d43e7c36'
down_revision = 'a0889f273a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.text("""CREATE EXTENSION IF NOT EXISTS pg_trgm"""))
    op.create_index('ix_gin_tags_tag', 'tags', ['tag'], unique=False, postgresql_using='gin', postgresql_ops={'tag': 'gin_trgm_ops'})
    op.create_unique_constraint('uq_tags_tag', 'tags', ['tag'])
    op.add_column('templates', sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'dt_updated')
    op.drop_constraint('uq_tags_tag', 'tags', type_='unique')
    op.drop_index('ix_gin_tags_tag', table_name='tags', postgresql_using='gin', postgresql_ops={'tag': 'gin_trgm_ops'})
    connection = op.get_bind()
    connection.execute(sa.text("""DROP EXTENSION IF EXISTS pg_trgm"""))
    # ### end Alembic commands ###
