"""empty message

Revision ID: 64b6e97e3d91
Revises: 817df4b08751
Create Date: 2022-11-26 19:23:54.426464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b6e97e3d91'
down_revision = '817df4b08751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.text("""CREATE EXTENSION IF NOT EXISTS pg_trgm"""))
    op.create_index('ix_gin_templates_title', 'templates', [sa.text('lower(title)')], unique=False, postgresql_using='gin', postgresql_ops={'lower(title)': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    op.drop_index('ix_gin_templates_title', table_name='templates', postgresql_using='gin', postgresql_ops={'lower(title)': 'gin_trgm_ops'})
    #connection.execute(sa.text("""DROP EXTENSION IF EXISTS pg_trgm CASCADE"""))
    # ### end Alembic commands ###
