"""empty message

Revision ID: 817df4b08751
Revises: ada707a62526
Create Date: 2022-11-26 17:41:05.597376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817df4b08751'
down_revision = 'ada707a62526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('preview_filename', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('templates', 'preview_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('preview_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('templates', 'preview_filename')
    # ### end Alembic commands ###
