"""empty message

Revision ID: a0889f273a65
Revises: 27b1565deb2c
Create Date: 2022-11-16 13:48:41.019581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0889f273a65'
down_revision = '27b1565deb2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates2tags_template_id_fkey', 'templates2tags', type_='foreignkey')
    op.drop_constraint('templates2tags_tag_id_fkey', 'templates2tags', type_='foreignkey')
    op.create_foreign_key('fk_templates2tags_template_id_templates', 'templates2tags', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_templates2tags_tag_id_tags', 'templates2tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_templates2tags_template_id_templates', 'templates2tags', type_='foreignkey')
    op.drop_constraint('fk_templates2tags_tag_id_tags', 'templates2tags', type_='foreignkey')
    op.create_foreign_key('templates2tags_tag_id_fkey', 'templates2tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('templates2tags_template_id_fkey', 'templates2tags', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###
