"""empty message

Revision ID: ada707a62526
Revises: 4c22d43e7c36
Create Date: 2022-11-24 13:36:23.820083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada707a62526'
down_revision = '4c22d43e7c36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('preview_url', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'preview_url')
    # ### end Alembic commands ###
