OWNER(g:divkit)

UNION()

FILES(
    generators/dart/__init__.py
    generators/dart/dart_entities.py
    generators/dart/generator.py
    generators/dart/utils.py
    generators/divan/__init__.py
    generators/divan/divan_entities.py
    generators/divan/generator.py
    generators/documentation/__init__.py
    generators/documentation/documentation_entities.py
    generators/documentation/generator.py
    generators/documentation/translations.py
    generators/documentation/utils.py
    generators/kotlin/__init__.py
    generators/kotlin/generator.py
    generators/kotlin/kotlin_entities.py
    generators/kotlin_dsl/__init__.py
    generators/kotlin_dsl/generator.py
    generators/kotlin_dsl/kotlin_dsl_entities.py
    generators/python/__init__.py
    generators/python/generator.py
    generators/python/python_entities.py
    generators/swift/__init__.py
    generators/swift/generator.py
    generators/swift/swift_entities.py
    generators/swift/utils.py
    generators/type_script/__init__.py
    generators/type_script/generator.py
    generators/type_script/typescript_entities.py
    generators/__init__.py
    generators/base.py
    schema/modeling/__init__.py
    schema/modeling/builders.py
    schema/modeling/entities.py
    schema/modeling/errors.py
    schema/modeling/modeler.py
    schema/modeling/text.py
    schema/modeling/utils.py
    schema/preprocessing/__init__.py
    schema/preprocessing/entities.py
    schema/preprocessing/errors.py
    schema/preprocessing/preprocessor.py
    schema/preprocessing/utils.py
    schema/__init__.py
    schema/utils.py
    __init__.py
    __main__.py
    config.py
    generator.py
    utils.py
)

END()
